#!/bin/bash

NTHREADS=2
SMOOTH_WINDOW=15
TEMPERATURE_MAX=50000
LTAU_MAX=2 

COMMAND="../src/depthOpt.x FALC_5x5.fits FALC_5x5_optimized.fits "
eval $COMMAND $NTHREADS 0 $SMOOTH_WINDOW $TEMPERATURE_MAX $LTAU_MAX

